# Generated by Django 4.0.4 on 2022-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HearthstoneState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='0.0.0', help_text='Current HS version', max_length=255, verbose_name='Version')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last update time')),
                ('success', models.BooleanField(default=False, help_text='Whether the last update was successful', verbose_name='Updated successfully')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
