# Generated by Django 4.0.4 on 2022-06-05 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='User-definable name', max_length=255, verbose_name='Name')),
                ('string', models.TextField(help_text='The string used to identify the cards that make up the deck.', max_length=1500, verbose_name='Deck code')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of creation')),
            ],
            options={
                'verbose_name': 'Deck',
                'verbose_name_plural': 'Decks',
                'ordering': ['-created'],
            },
            managers=[
                ('nameless', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(default='Unknown', max_length=255, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(default='Unknown', max_length=255, null=True, verbose_name='Name')),
                ('numerical_designation', models.PositiveSmallIntegerField(default=0, verbose_name='Format code')),
            ],
            options={
                'verbose_name': 'Format',
                'verbose_name_plural': 'Formats',
            },
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('render', models.ImageField(blank=True, null=True, upload_to='decks/', verbose_name='Render')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский')], default='en', max_length=2)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='decks.deck', verbose_name='Deck')),
            ],
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='The number of card inclusions in the deck.', verbose_name='Amount')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='cards.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='decks.deck')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(help_text='The cards that make up the deck.', through='decks.Inclusion', to='cards.card', verbose_name='Cards'),
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_class',
            field=models.ForeignKey(help_text='The class for which the deck is built.', on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='cards.cardclass', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_format',
            field=models.ForeignKey(help_text='The format for which the deck is intended.', on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='decks.format', verbose_name='Format'),
        ),
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
