# Generated by Django 4.0.4 on 2023-04-01 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_card_type'),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusion',
            name='is_native',
            field=models.BooleanField(default=True, help_text='Is the card included in the deck by default'),
        ),
        migrations.AddField(
            model_name='inclusion',
            name='source_card',
            field=models.ForeignKey(blank=True, help_text='The card by which this card was added.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inclusion_source', to='cards.card'),
        ),
    ]
