# Generated by Django 4.0.4 on 2022-07-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('', '---------'), ('M', 'Minion'), ('S', 'Spell'), ('H', 'Hero'), ('W', 'Weapon'), ('HP', 'Hero power'), ('L', 'Location')], default='', max_length=2, verbose_name='Type'),
        ),
    ]
